runtime: python37

entrypoint: gunicorn -b :$PORT fs_flask:fs_app

handlers:
  - url: /static
    static_dir: fs_flask/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "google-cloud.json"
  ENVIRONMENT: "prod"
